services:
  be:
    image: quangtrong10/cinema:latest
#    image: cinema:latest
    ports:
      - "80:8088"
    depends_on:
      - db
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_HOST: ${SPRING_DATASOURCE_SERVER_HOST}
      SPRING_DATASOURCE_PORT: ${SPRING_DATASOURCE_PORT}
      SPRING_DATASOURCE_DB: ${SPRING_DATASOURCE_DB}
      SPRING_DATASOURCE_USE_SSL: ${SPRING_DATASOURCE_USE_SSL}
      SPRING_DATASOURCE_ALLOW_PUBLIC_KEY_RETRIEVAL: ${SPRING_DATASOURCE_ALLOW_PUBLIC_KEY_RETRIEVAL}
      SPRING_DATASOURCE_SERVER_TIMEZONE: ${SPRING_DATASOURCE_SERVER_TIMEZONE}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_SERVER_PASSWORD}

      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      OTP_EXPIRY_MINUTES: ${OTP_EXPIRY_MINUTES}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}

      API_NTQ_CINEMA_URL: ${API_NTQ_CINEMA_URL}

      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

      VNPAY_URL: ${VNPAY_URL}
      VNPAY_RETURN_URL: ${VNPAY_RETURN_URL}
      VNPAY_TMN_CODE: ${VNPAY_TMN_CODE}
      VNPAY_HASH_SECRET: ${VNPAY_HASH_SECRET}


  db:
    image: mysql:8
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_SERVER_PASSWORD}
        MYSQL_DATABASE: ${SPRING_DATASOURCE_DB}

    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: